blogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.apps import BlogsConfig
from blogs.views import BlogCreateView, BlogListView, BlogDeleteView, BlogDetailView, BlogUpdateView

app_name = BlogsConfig.name

urlpatterns = [
    path('blogs', cache_page(15)(BlogListView.as_view()), name='blogs'),
    path('create_blogs', BlogCreateView.as_view(), name='blogs_create'),
    path('update_blog/<int:pk>', BlogUpdateView.as_view(), name='update_blog'),
    path('detail_blog/<int:pk>', BlogDetailView.as_view(), name='detail_blog'),
    path('delete_blog/<int:pk>', BlogDeleteView.as_view(), name='delete_blog'),
]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import home, UserCreateView, MailCreateView, MailListView, MailDeleteView, MailDetailView, UserListView, \
    UserUpdateView, UserDeleteView, SuccessMailListView, MailUpdateView

app_name = MainConfig.name

urlpatterns = [
    path('', home, name="home"),
    path('create_user', UserCreateView.as_view(), name="create_user"),
    path('create_mail', MailCreateView.as_view(), name="create_mail"),
    path('mails', MailListView.as_view(), name="mails"),
    path('success_mails', SuccessMailListView.as_view(), name="success_mails"),
    path('users', UserListView.as_view(), name="users"),
    path('delete_mail/<int:pk>', MailDeleteView.as_view(), name="delete_mails"),
    path('detail_mail/<int:pk>', MailDetailView.as_view(), name="detail_mails"),
    path('delete_user/<int:pk>', UserDeleteView.as_view(), name="delete_users"),
    path('edit_user/<int:pk>', UserUpdateView.as_view(), name="edit_users"),
    path('edit_mail/<int:pk>', MailUpdateView.as_view(), name="edit_mails"),
]

service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('', include('users.urls', namespace="users")),
    path('', include('blogs.urls', namespace="blogs")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models

from users.models import User


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок')
    body = models.TextField(verbose_name='Содержимое статьи')
    image = models.ImageField(verbose_name='Изображение', null=True, blank=True)
    views = models.IntegerField(default=0, verbose_name='Кол-во просмотров')
    date = models.DateTimeField(verbose_name='Дата публикации')

    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='автор')

    def __str__(self):
        return f'{self.title} {self.body} {self.image} {self.views} {self.date}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

blogs/forms.py
from django import forms

from blogs.models import Blog
from main.forms import StyleForm

class BlogCreateForm(StyleForm, forms.ModelForm):

    class Meta:
        model = Blog
        fields = ('image', 'title', 'body')

blogs/views.py
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.models import Group
from django.urls import reverse_lazy
from django.utils import timezone
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView

from blogs.forms import BlogCreateForm
from blogs.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    form_class = BlogCreateForm
    success_url = reverse_lazy('blogs:blogs')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.date = timezone.now()
        self.object.save()
        return super().form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        context_data['title'] = 'Создайте свой блог'

        return context_data

class BlogListView(ListView):
    model = Blog
    template_name = 'blogs/blogs.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['is_manager'] = False
        if Group.objects.get(name='Менеджеры') in self.request.user.groups.all():
            context_data['is_manager'] = True
        context_data['title'] = 'Блоги'

        return context_data

class BlogDetailView(LoginRequiredMixin, DetailView):
    model = Blog

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        context_data['title'] = 'Блог'

        return context_data

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object

class BlogUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Blog
    form_class = BlogCreateForm
    success_url = reverse_lazy(f'blogs:blogs')

    def test_func(self):
        mail = self.get_object()

        return mail.author == self.request.user or Group.objects.get(name='Менеджеры') in self.request.user.groups.all()

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        context_data['title'] = 'Измените блог по своему усмотрению'

        return context_data

class BlogDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blogs:blogs')

    def test_func(self):
        mail = self.get_object()
        return mail.author == self.request.user or Group.objects.get(name='Менеджеры') in self.request.user.groups.all()

blogs/templates/blogs/blog_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-6" style="margin-left:220px">
    <div class="card text-bg-primary mb-3">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>Подтвердите удаление блога под названием <p style="color:red">"{{ object.title | truncatewords:20 }}"</p></p>
                <button type="submit" class="btn btn-primary">Подтвердить</button>
                <a href="{% url 'blogs:blogs' %}" class="btn btn-danger">Отменить</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/blog_detail.html
{% extends 'main/base.html' %}
{% block content %}
<div class="card mb-3">
    <img class="card-img-top" src="{{ object.image.url}}" alt="..." width="300px" height="400px">
    <div class="card-body">
        <h5 class="card-title">{{object.title}}</h5>
        <p class="card-text"><small class="text-muted">{{object.body}}</small></p>
        <div class="like_views like_views--inActionPanel" role="img">
                <span class="like_views__icon "><svg fill="none" height="16" viewBox="0 0 16 16" width="16"
                                                     xmlns="http://www.w3.org/2000/svg"><g fill="currentColor"><path
                        d="M9.5 8a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"></path><path clip-rule="evenodd"
                                                                                     d="M15.5 8c0-1-3-5-7.5-5S.5 7 .5 8s3 5 7.5 5 7.5-4 7.5-5zm-4 0a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z"
                                                                                     fill-rule="evenodd"></path></g></svg></span>
            <span class="_views">{{object.views}}</span>
            <p class="card-text"><small class="text-muted">{{object.date}}</small></p>
        </div>
    </div>
</div>
    {% endblock %}

blogs/templates/blogs/blog_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-6" style="margin-left:220px">
    <div class="card text-bg-primary mb-3">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {{form.as_p}}

                {% if object %}
                <button type="submit" class="btn btn-primary mb-3">Изменить</button>
                {% else %}
                <button type="submit" class="btn btn-primary mb-3">Создать</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

blogs/templates/blogs/blogs.html
{% extends 'main/base.html' %}
{% block content %}
{% for object in object_list %}
<div class="col-md-4">
    <div class="card mb-4 box-shadow">
        <div class="card">
            <img class="card-img-top" src="{{ object.image.url }}" height="400px" width="200px">
            <div class="card-body" align="center">
                <h4 class="card-title">{{object.title | title | truncatewords:30}}</h4>
                <p>{{object.date}}</p>
            </div>
            <div class="card-body" align="center">
                <a href="{% url 'blogs:detail_blog' object.pk %}" class="card-link">Подробнее</a>
                {% if user == object.author or is_manager %}
                <a href="{% url 'blogs:update_blog' object.pk %}" class="card-link">Изменить</a>
                <a href="{% url 'blogs:delete_blog' object.pk %}" class="card-link">Удалить</a>
                {% endif %}
            </div>
            <div class="like_views like_views--inActionPanel" role="img"
            ">
            <span class="like_views__icon "><svg fill="none" height="16" viewBox="0 0 16 16" width="16"
                                                 xmlns="http://www.w3.org/2000/svg"><g fill="currentColor"><path
                    d="M9.5 8a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"></path><path clip-rule="evenodd"
                                                                                 d="M15.5 8c0-1-3-5-7.5-5S.5 7 .5 8s3 5 7.5 5 7.5-4 7.5-5zm-4 0a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z"
                                                                                 fill-rule="evenodd"></path></g></svg></span>
            <span class="_views">{{object.views}}</span>
        </div>
    </div>
</div>
</div>
{% endfor %}
{% endblock %}