main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import home, UserCreateView, MailCreateView, MailListView, MailDeleteView, MailDetailView, UserListView, \
    UserUpdateView, UserDeleteView, SuccessMailListView, MailUpdateView

app_name = MainConfig.name

urlpatterns = [
    path('', home, name="home"),
    path('create_user', UserCreateView.as_view(), name="create_user"),
    path('create_mail', MailCreateView.as_view(), name="create_mail"),
    path('mails', MailListView.as_view(), name="mails"),
    path('success_mails', SuccessMailListView.as_view(), name="success_mails"),
    path('users', UserListView.as_view(), name="users"),
    path('delete_mail/<int:pk>', MailDeleteView.as_view(), name="delete_mails"),
    path('detail_mail/<int:pk>', MailDetailView.as_view(), name="detail_mails"),
    path('delete_user/<int:pk>', UserDeleteView.as_view(), name="delete_users"),
    path('edit_user/<int:pk>', UserUpdateView.as_view(), name="edit_users"),
    path('edit_mail/<int:pk>', MailUpdateView.as_view(), name="edit_mails"),
]

service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('', include('users.urls', namespace="users")),
    path('', include('blogs.urls', namespace="blogs")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy

from users.views import RegisterView, ProfileView, send_verification_email, verify_email, UsersListView, \
    UsersDetailView, block_user, unblock_user
from users.apps import UsersConfig


app_name = UsersConfig.name

urlpatterns = [
    path('login', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', LogoutView.as_view(next_page=reverse_lazy('main:home')), name='logout'),
    path('register', RegisterView.as_view(), name='register'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('verify', send_verification_email, name='verify'),
    path('verification/verify/<str:uid64>/<str:token>', verify_email, name='verify_email'),
    path('view_users', UsersListView.as_view(), name='view_users'),
    path('detail_users/<int:pk>', UsersDetailView.as_view(), name='detail_users'),
    path('block_users/<int:pk>', block_user, name='block_users'),
    path('unblock_users/<int:pk>', unblock_user, name='unblock_users'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser, models.Model):
    username = None

    email = models.EmailField(unique=True, verbose_name='почта')

    avatar = models.ImageField(upload_to='users/avatars/', default='avatars/standart_avatar.png', verbose_name='аватар *Необязательное поле', null=True, blank=True)
    is_email_verified = models.BooleanField(default=False, verbose_name='статус верификации почты')
    is_blocked = models.BooleanField(default=False, verbose_name='Статус блокировки')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

users/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User
from main.forms import StyleForm

class UserRegisterForm(StyleForm, UserCreationForm):

    class Meta:
        model = User
        fields = ('avatar', 'email', 'first_name', 'last_name', 'password1', 'password2')


class UserProfileForm(StyleForm, UserChangeForm):
    class Meta:
        model = User
        fields = ('avatar', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from users.models import User
from users.forms import UserRegisterForm, UserProfileForm


@login_required(login_url='users:login')
def send_verification_email(request):
    current_site = get_current_site(request)
    mail_subject = "Подтвердите свою почту"
    message = render_to_string('users/verification_email.html', {
        'user': request.user,
        'domain': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(request.user.pk)),
        'token': default_token_generator.make_token(request.user)
    })
    send_mail(mail_subject, message, 'sendinfoforauth@gmail.com', [request.user.email])

    return render(request, 'users/verification_sent.html')

@login_required(login_url='users:login')
def verify_email(request, uid64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uid64))
        user = get_user_model().objects.get(pk=uid)
    except:
        user = None

    else:
        if user is not None and default_token_generator.check_token(user, token):
            user.is_email_verified = True
            user.save()
            return render(request, 'users/success_verification.html')
        else:
            return render(request, 'users/error_verification.html')

class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Зарегистрируйтесь для использования сервиса'

        return context_data

class ProfileView(LoginRequiredMixin,UpdateView):
    login_url = 'users:login'
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        email = self.request.user.email

        context_data['title'] = 'Здесь вы можете изменить свои данные'
        context_data['page_info'] = email

        return context_data

class UsersListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    login_url = 'users:login'
    model = User
    template_name = 'users/view_users.html'
    permission_required = 'user.view_user'

class UsersDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    login_url = 'users:login'
    model = User
    template_name = 'users/detail_user.html'
    permission_required = 'user.view_user'

@permission_required('user.change_user')
def block_user(request, pk):
    user = get_object_or_404(User, id=pk)
    user.is_blocked = True
    user.save()

    return render(request, 'users/user_blocked.html', context={'text': f'Пользователь {user.email} был успешно заблокирован'})

@permission_required('user.change_user')
def unblock_user(request, pk):
    user = get_object_or_404(User, id=pk)
    user.is_blocked = False
    user.save()

    return render(request, 'users/user_blocked.html', context={'text': f'Пользователь {user.email} был успешно разблокирован'})

users/templates/users/detail_user.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <h4><b>Аватар:</b></h4>
              <img class="profile-img" src="{{object.avatar.url}}" alt="User Image" height="200px" width="200px">
                <ul class="list-unstyled mt-3 mb-4">
                    <h4><b>Почта:</b></h4>
                  <li>{{object.email}}</li>
                    <h4><b>Имя:</b></h4>
                  <li>{{object.first_name}}</li>
                    <h4><b>Фамилия:</b></h4>
                  <li>{{object.last_name}}</li>
                    <h4><b>Статус верификации:</b></h4>
                  <li>{{object.is_verified}}</li>
                    <h4><b>Статус:</b></h4>
                  <li>{{object.is_blocked}}</li>
                </ul>
            </div>
            {% if not object.is_blocked %}
            <a href="{% url 'users:block_users' object.pk %}" class="btn btn-danger btn-lg btn-block custom-button">Заблокировать</a>
            {% else %}
            <a href="{% url 'users:unblock_users' object.pk %}" class="btn btn-success btn-lg btn-block">Разблокировать</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/error_verification.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-4" style="margin-left:300px">
    <h3 style="white-space: nowrap;">Ошибка в верификации почты</h3>
    <a href="{% url 'users:login' %}" class="btn btn-primary my-2">Войти</a>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-6" style="margin-left:220px">
    <div style="margin-left:30px; margin-bottom: 20px;">
        <h3> Войдите, чтобы продолжить </h3>
    </div>
    <div class="card text-bg-primary mb-3">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {{form.as_p}}

                <button type="submit" class="btn btn-primary mb-3">Войти</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-6" style="margin-left:220px">
    <div align="center" style="margin-bottom: 15px;">
    {% if not user.is_email_verified %}
            <h5 style="color:red" align="center">Вы еще не подтвердили свою почту!</h5>
            <a href="{% url 'users:verify' %}" class="btn btn-success mb-3">Подтвердить</a>
            {% endif %}
        </div>
    <div class="card text-bg-primary mb-3">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {{form.as_p}}

                <button type="submit" class="btn btn-primary mb-3">Изменить</button>
            </form>
            <a href="{% url 'users:logout' %}" class="btn btn-danger mb-3">Выйти из аккаунта</a>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-6" style="margin-left:220px">
    <div class="card text-bg-primary mb-3">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                {{form.as_p}}

                <button type="submit" class="btn btn-primary mb-3">Зарегистрироваться</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/success_verification.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-4" style="margin-left:300px">
    <h3 style="white-space: nowrap;">Вы успешно верифицировали свою почту!</h3>
</div>

{% endblock %}

users/templates/users/user_blocked.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-4" style="align:center;">
    <h3 style="white-space: nowrap;">{{text}}</h3>
</div>

{% endblock %}

users/templates/users/verification_email.html
Пожалуйста, подтвердите свою почту, перейдя по следующей ссылке:
http://{{ domain }}/verification/verify/{{ uid }}/{{ token }}

users/templates/users/verification_sent.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-4" style="align:center;">
    <h3 style="white-space: nowrap;">Ссылка на верификацию успешно отправлена на вашу почту</h3>
</div>

{% endblock %}

users/templates/users/view_users.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container">
  {% for object in object_list %}
<div class="card mb-3">
  <img src="{{object.avatar.url}}" class="card-img-top" alt="avatar" height="600px">
  <div class="card-body">
    <h3 class="card-title">{{object.first_name}}</h3>
    <h3 class="card-title">{{object.last_name}}</h3>
    <h6 class="card-title">{{object.email}}</h6>
    <p class="card-text">{{object.comment}}</p>
    <a href="{% url 'users:detail_users' object.pk %}" class="btn btn-info btn-lg btn-block">Подробнее</a>
  </div>
</div>
    {%endfor%}
</div>

{% endblock %}