blogs/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blogs.apps import BlogsConfig
from blogs.views import BlogCreateView, BlogListView, BlogDeleteView, BlogDetailView, BlogUpdateView

app_name = BlogsConfig.name

urlpatterns = [
    path('blogs', cache_page(15)(BlogListView.as_view()), name='blogs'),
    path('create_blogs', BlogCreateView.as_view(), name='blogs_create'),
    path('update_blog/<int:pk>', BlogUpdateView.as_view(), name='update_blog'),
    path('detail_blog/<int:pk>', BlogDetailView.as_view(), name='detail_blog'),
    path('delete_blog/<int:pk>', BlogDeleteView.as_view(), name='delete_blog'),
]

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import home, UserCreateView, MailCreateView, MailListView, MailDeleteView, MailDetailView, UserListView, \
    UserUpdateView, UserDeleteView, SuccessMailListView, MailUpdateView

app_name = MainConfig.name

urlpatterns = [
    path('', home, name="home"),
    path('create_user', UserCreateView.as_view(), name="create_user"),
    path('create_mail', MailCreateView.as_view(), name="create_mail"),
    path('mails', MailListView.as_view(), name="mails"),
    path('success_mails', SuccessMailListView.as_view(), name="success_mails"),
    path('users', UserListView.as_view(), name="users"),
    path('delete_mail/<int:pk>', MailDeleteView.as_view(), name="delete_mails"),
    path('detail_mail/<int:pk>', MailDetailView.as_view(), name="detail_mails"),
    path('delete_user/<int:pk>', UserDeleteView.as_view(), name="delete_users"),
    path('edit_user/<int:pk>', UserUpdateView.as_view(), name="edit_users"),
    path('edit_mail/<int:pk>', MailUpdateView.as_view(), name="edit_mails"),
]

service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="main")),
    path('', include('users.urls', namespace="users")),
    path('', include('blogs.urls', namespace="blogs")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy

from users.views import RegisterView, ProfileView, send_verification_email, verify_email, UsersListView, \
    UsersDetailView, block_user, unblock_user
from users.apps import UsersConfig


app_name = UsersConfig.name

urlpatterns = [
    path('login', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout', LogoutView.as_view(next_page=reverse_lazy('main:home')), name='logout'),
    path('register', RegisterView.as_view(), name='register'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('verify', send_verification_email, name='verify'),
    path('verification/verify/<str:uid64>/<str:token>', verify_email, name='verify_email'),
    path('view_users', UsersListView.as_view(), name='view_users'),
    path('detail_users/<int:pk>', UsersDetailView.as_view(), name='detail_users'),
    path('block_users/<int:pk>', block_user, name='block_users'),
    path('unblock_users/<int:pk>', unblock_user, name='unblock_users'),
]

main/forms.py
from django import forms
from django.forms import DateTimeInput

from main.models import Client, Mails

class StyleForm:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name in ('scheduled', 'end'):
                field.widget = DateTimeInput(attrs={'type': 'datetime-local', 'class' : 'form-control'})
            else:
                field.widget.attrs['class'] = 'form-control'
class UserForm(StyleForm, forms.ModelForm):

    class Meta:
        model = Client
        fields = ('avatar', 'name', 'email', 'comment')

class MailForm(StyleForm, forms.ModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['users'].queryset = Client.objects.filter(author=user)

    users = forms.ModelMultipleChoiceField(queryset=Client.objects.none(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Mails
        fields = ('users', 'theme', 'body', 'scheduled', 'periodic', 'end')

    def clean_periodic(self):
        cleaned_data = self.cleaned_data.get('periodic')

        if cleaned_data and cleaned_data > 360:
            raise forms.ValidationError('Значение не может быть больше 360')

        return cleaned_data

    def clean(self):
        cleaned_data = super().clean()
        field1 = cleaned_data.get('periodic')
        field2 = cleaned_data.get('end')

        if field1 and not field2:
            raise forms.ValidationError("Для использования периодичной рассылки требуется указание времени окончания рассылки")

        if field2 and not field1:
            raise forms.ValidationError("Интервал между рассылками не указан")

        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.dynamic_periodic = self.cleaned_data['periodic']
        if commit:
            instance.save()
        return instance

class MailUpdateForm(StyleForm, forms.ModelForm):

    class Meta:
        model = Mails
        fields = ('theme', 'body',)

main/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import Group
from django.db.models import Count
from django.shortcuts import render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView
from django.utils import timezone


from main.models import Client, Mails
from main.forms import UserForm, MailForm, MailUpdateForm

from blogs.models import Blog

class Blogs:
    pass


@cache_page(15)
def home(request):
    count = Mails.objects.count()
    count_active = Mails.objects.filter(status=False).count()
    
    blogs = Blog.objects.order_by('?')[:3]

    clients = []

    all_emails = Mails.objects.all()

    for email in all_emails:
        for client in email.users.all():
            if client.email not in clients:
                clients.append(client.email)
    if request.user.is_authenticated:
        page_info = f'Вы авторизованы как {request.user.email}'
    else:
        page_info = f'Вы еще не авторизованы'

    context = {
        'title': 'Главная',
        'page_info': f'Это сервис по управлению рассылками. {page_info}',
        'count' : count,
        'count_active' : count_active,
        'count_clients': len(clients),
        'object_list': blogs,
    }
    return render(request, 'main/index.html', context)


class UserCreateView(LoginRequiredMixin, CreateView):
    login_url = 'users:login'
    model = Client
    form_class = UserForm
    success_url = reverse_lazy('main:home')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Создать пользователя'
        context_data['page_info'] = ''
        return context_data

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        self.object = form.save()
        self.object.author = self.request.user
        user = form.save(commit=False)
        user.save()
        return super().form_valid(form)

class UserListView(LoginRequiredMixin, ListView):
    login_url = 'users:login'
    model = Client
    template_name = 'main/users_view.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Список всех клиентов, зарегистрированных в системе'

        return context_data

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if not Group.objects.get(name='Менеджеры') in self.request.user.groups.all():
            queryset = queryset.filter(author=self.request.user)
        queryset = queryset.annotate(mails_count=Count('mails'))

        return queryset

class UserDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    login_url = 'users:login'
    model = Client
    success_url = reverse_lazy('main:home')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Подтвердите удаление клиента'
        context_data['page_info'] = 'После удаления клиента все рассылки, которые ссылаются на email клиента будут отменены'

        return context_data
    def test_func(self):
        mail = self.get_object()

        return mail.author == self.request.user or Group.objects.get(name='Менеджеры') in self.request.user.groups.all()

class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    login_url = 'users:login'
    model = Client
    form_class = UserForm
    success_url = reverse_lazy('main:users')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Внесите желаемые изменения'
        context_data['page_info'] = ''

        return context_data
    def test_func(self):
        client = self.get_object()

        return client.author == self.request.user or Group.objects.get(name='Менеджеры') in self.request.user.groups.all()

class MailCreateView(LoginRequiredMixin, CreateView):
    login_url = 'users:login'
    model = Mails
    form_class = MailForm
    success_url = reverse_lazy('main:home')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs
    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Создать рассылку'
        context_data['page_info'] = 'Время необходимо вводить в формате GMT+0'
        context_data['info'] = 'При неуказывании запланированной даты, рассылка начнется мгновенно'
        return context_data

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        self.object = form.save()
        self.object.author = self.request.user
        users = form.cleaned_data["users"]
        self.object.users.set(users)

        return super().form_valid(form)

class MailListView(ListView):
    model = Mails
    template_name = 'main/mails_view.html'

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Все рассылки, включая созданные'
        context_data['is_success'] = False

        return context_data or Group.objects.get(name='Менеджеры') in self.request.user.groups.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        if not Group.objects.get(name='Менеджеры') in self.request.user.groups.all():
            queryset = queryset.filter(author=self.request.user)

        return queryset


class SuccessMailListView(ListView):
    model = Mails
    template_name = 'main/mails_view.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        if not Group.objects.get(name='Менеджеры') in self.request.user.groups.all():
            queryset = queryset.filter(author=self.request.user, status=True)

        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Список всех проведенных рассылок'
        context_data['is_success'] = True

        return context_data


class MailDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    login_url = 'users:login'
    model = Mails
    success_url = reverse_lazy('main:mails')

    def test_func(self):
        mail = self.get_object()

        return mail.author == self.request.user or Group.objects.get(name='Менеджеры') in self.request.user.groups.all()
    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Подтвердите отмену рассылки'
        context_data['page_info'] = 'После подтверждения все запланированные рассылки будут отменены'

        return context_data

class MailDetailView(LoginRequiredMixin, DetailView):
    login_url = 'users:login'
    model = Mails

    def test_func(self):
        mail = self.get_object()

        return mail.author == self.request.user or Group.objects.get(name='Менеджеры') in self.request.user.groups.all()
    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = f'Информация о рассылке'

        if self.object.scheduled and self.object.scheduled <= timezone.now():
            context_data['zapusheno'] = 'Запущена'
        else:
            context_data['zapusheno'] = ''

        return context_data

class MailUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'users:login'
    model = Mails
    form_class = MailUpdateForm
    success_url = reverse_lazy('main:mails')

    def test_func(self):
        mail = self.get_object()

        return mail.author == self.request.user

users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import CreateView, UpdateView, ListView, DetailView, DeleteView

from users.models import User
from users.forms import UserRegisterForm, UserProfileForm


@login_required(login_url='users:login')
def send_verification_email(request):
    current_site = get_current_site(request)
    mail_subject = "Подтвердите свою почту"
    message = render_to_string('users/verification_email.html', {
        'user': request.user,
        'domain': current_site.domain,
        'uid': urlsafe_base64_encode(force_bytes(request.user.pk)),
        'token': default_token_generator.make_token(request.user)
    })
    send_mail(mail_subject, message, 'sendinfoforauth@gmail.com', [request.user.email])

    return render(request, 'users/verification_sent.html')

@login_required(login_url='users:login')
def verify_email(request, uid64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uid64))
        user = get_user_model().objects.get(pk=uid)
    except:
        user = None

    else:
        if user is not None and default_token_generator.check_token(user, token):
            user.is_email_verified = True
            user.save()
            return render(request, 'users/success_verification.html')
        else:
            return render(request, 'users/error_verification.html')

class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = 'Зарегистрируйтесь для использования сервиса'

        return context_data

class ProfileView(LoginRequiredMixin,UpdateView):
    login_url = 'users:login'
    model = User
    form_class = UserProfileForm
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        email = self.request.user.email

        context_data['title'] = 'Здесь вы можете изменить свои данные'
        context_data['page_info'] = email

        return context_data

class UsersListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    login_url = 'users:login'
    model = User
    template_name = 'users/view_users.html'
    permission_required = 'user.view_user'

class UsersDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    login_url = 'users:login'
    model = User
    template_name = 'users/detail_user.html'
    permission_required = 'user.view_user'

@permission_required('user.change_user')
def block_user(request, pk):
    user = get_object_or_404(User, id=pk)
    user.is_blocked = True
    user.save()

    return render(request, 'users/user_blocked.html', context={'text': f'Пользователь {user.email} был успешно заблокирован'})

@permission_required('user.change_user')
def unblock_user(request, pk):
    user = get_object_or_404(User, id=pk)
    user.is_blocked = False
    user.save()

    return render(request, 'users/user_blocked.html', context={'text': f'Пользователь {user.email} был успешно разблокирован'})

main/templates/main/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>{{title}}</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/pricing.css" rel="stylesheet">
</head>

<body>

{% include 'main/includes/inc_main_menu.html' %}

<main role="main">

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-4">{{title}}</h1>
        <p class="lead">{{page_info}}</p>
    </div>

    <div class="container">
        {% block content %}
        {% endblock %}
        <footer class="pt-4 my-md-5 pt-md-5 border-top">
            <div class="row">
                <div class="col-12 col-md">
                    <small class="d-block mb-3 text-muted">&copy; 2023</small>
                </div>
                <div class="col-6 col-md">
                    <h5>Features</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Cool stuff</a></li>
                        <li><a class="text-muted" href="#">Random feature</a></li>
                        <li><a class="text-muted" href="#">Team feature</a></li>
                        <li><a class="text-muted" href="#">Stuff for developers</a></li>
                        <li><a class="text-muted" href="#">Another one</a></li>
                        <li><a class="text-muted" href="#">Last time</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>Resources</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Resource</a></li>
                        <li><a class="text-muted" href="#">Resource name</a></li>
                        <li><a class="text-muted" href="#">Another resource</a></li>
                        <li><a class="text-muted" href="#">Final resource</a></li>
                    </ul>
                </div>
                <div class="col-6 col-md">
                    <h5>About</h5>
                    <ul class="list-unstyled text-small">
                        <li><a class="text-muted" href="#">Team</a></li>
                        <li><a class="text-muted" href="#">Locations</a></li>
                        <li><a class="text-muted" href="#">Privacy</a></li>
                        <li><a class="text-muted" href="#">Terms</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>

    <script src="/static/js/pooper.min.js"></script>
    <script src="/static/bootstrap.min.js"></script>
    <script src="/static/js/holder.min.js"></script>
    <style>
.custom-button {
  background-color: transparent;
  border-color: red;
  color: red;
  transition: background-color 0.3s;
}

.custom-button:hover {
  background-color: red;
  color: white;
}

    </style>

</body>
</html>

main/templates/main/client_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-6" style="margin-left:220px">
    <div class="card text-bg-primary mb-3">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>Подтвердите удаление клиента <p style="color: red;">{{object.email}}</p></p>
                <button type="submit" class="btn btn-primary">Подтвердить</button>
                <a href="{% url 'main:home' %}" class="btn btn-danger">Отменить</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/client_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="col-md-6" style="margin-left:220px">
    <div class="card text-bg-primary mb-3">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                {% if object %}
                <button type="submit" class="btn btn-primary">Изменить</button>
                {% else %}
                <button type="submit" class="btn btn-primary">Создать</button>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/email_sent.html
{% extends 'main/base.html' %}
{% block content %}
<h3>Рассылка успешно отправлена</h3>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">За все время было сделано</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title mb-5">{{count}} рассылок</h1>
                <a href="{% url 'main:mails' %}" class="btn btn-block btn-info">Посмотреть расссылки</a>
            </div>
        </div>
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Кол-во активных рассылок на данный момент</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title mb-5">{{count_active}}</h1>
                <a href="{% url 'main:create_mail'%}" class="btn btn-block btn-info">Создать рассылку</a>
            </div>
        </div>
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Кол-во уникальных рассылок для клиента</h4>
            </div>
            <div class="card-body">
                <h1 class="card-title pricing-card-title mb-5">{{count_clients}} </h1>
                <a href="{% url 'main:users' %}" class="btn btn-block btn-info">Посмотреть список всех клиентов</a>
            </div>
        </div>
        {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card">
                    <img class="card-img-top" src="{{ object.image.url }}" height="400px" width="200px">
                    <div class="card-body" align="center">
                        <h4 class="card-title">{{object.title | title | truncatewords:30}}</h4>
                        <p>{{object.date}}</p>
                    </div>
                    <div class="card-body" align="center">
                        <a href="{% url 'blogs:detail_blog' object.pk %}" class="card-link">Подробнее</a>
                    </div>
                    <div class="like_views like_views--inActionPanel" role="img"
                    ">
                    <span class="like_views__icon "><svg fill="none" height="16" viewBox="0 0 16 16" width="16"
                                                         xmlns="http://www.w3.org/2000/svg"><g fill="currentColor"><path
                            d="M9.5 8a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"></path><path clip-rule="evenodd"
                                                                                         d="M15.5 8c0-1-3-5-7.5-5S.5 7 .5 8s3 5 7.5 5 7.5-4 7.5-5zm-4 0a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0z"
                                                                                         fill-rule="evenodd"></path></g></svg></span>
                    <span class="_views">{{object.views}}</span>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
</div>

{% endblock %}

main/templates/main/mails_detail.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="card-deck mb-3 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <b>Пользователю(-ям):  </b>
                    {% for user in object.users.all %}
                    <li> {{user}}</li>
                    {% endfor %}
                    <b>Тема письма:  </b>
                    <li>{{ object.theme }}</li>
                    <b>Текст письма:  </b>
                    <li>{{ object.body }}</li>
                    {% if object.scheduled %}
                    <b>Запланированное время отправки письма:  </b>
                    <li>{{ object.scheduled }} GMT+0</li>
                    {% endif %}
                    {% if object.dynamic_periodic %}
                    <b>Периодичность:  </b>
                    <li>Каждые {{ object.dynamic_periodic }} минут</li>
                    <b>До следующей попытки осталось:  </b>
                    <li>{{ object.periodic }} минут</li>
                    <b>Время окончания отправки писем: </b>
                    <li>{{ object.end }} GMT+0</li>
                    {% endif %}
                    <b>Статус:  </b>
                    <li>{%if object.status %} Завершена {% elif zapusheno %} {{zapusheno}} {% else %} Создана {% endif %}</li>
                </ul>

                <h3> <b>Логи</b> </h3>
                <ul class="list-unstyled mt-3 mb-4">
                    <b>Последняя попытка:  </b>
                    <li>{% if object.logs.last_time %}{{object.logs.last_time}} GMT+0 {% else %} Нет данных {% endif %}</li>
                    <b>Статус:  </b>
                    <li>{% if object.logs.status != None %}{% if object.logs.status %}Успешно {% else %} Ошибка {% endif %} {% else %} Нет данных {% endif %}</li>
                    <b>Ответ почтового сервера:  </b>
                    <li>{% if not object.logs.response is None %} {{ object.logs.response}} {% else %} Нет данных {% endif %}</li>
                <a href="{% url 'main:mails' %}" class="btn btn-lg btn-block btn-outline-primary">Вернуться на главную</a>
                <a href="{% url 'main:delete_mails' object.pk %}" class="btn btn-danger btn-lg btn-block custom-button">Отменить рассылку</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/mails_view.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container">
  {% for object in object_list %}
<div class="card-deck mb-5 text-center">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <ul class="list-unstyled mt-3 mb-4">
                    <li>{{object.subj.email}}</li>
                    <li>{{object.theme}}</li>
                    <li>{% if object.status %} Завершена {% else %} Создана {% endif %}</li>
                </ul>
                <a href="{% url 'main:detail_mails' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Подробности</a>
                {% if user == object.author %}
                <a href="{% url 'main:edit_mails' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Изменить рассылку</a>
                {% endif %}
                <a href="{% url 'main:delete_mails' object.pk %}" class="btn btn-danger btn-lg btn-block custom-button">Отменить рассылку</a>
            </div>

        </div>
    </div>
    {%endfor%}
    <div class="mb-5">
    {% if not is_success %}<a href="{% url 'main:success_mails' %}" class="btn btn-lg btn-block btn-success">Завершенные рассылки</a>{% endif %}
    </div>
</div>

{% endblock %}

main/templates/main/send_email.html
{{theme}}
{{body}}

Рассылка от ...

main/templates/main/users_view.html
{% extends 'main/base.html' %}
{% block content %}

<div class="container">
  {% for object in object_list %}
<div class="card mb-3">
  <img src="{{object.avatar.url}}" class="card-img-top" alt="avatar" height="600px">
  <div class="card-body">
    <h3 class="card-title">{{object.name}}</h3>
    <h6 class="card-title">{{object.email}}</h6>
    <p class="card-text">{{object.comment}}</p>
    <p class="card-text"><small class="text-body-secondary">Связанные рассылки: {{object.mails_count}}</small></p>
    <a href="{% url 'main:edit_users' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Изменить данные клиента</a>
    <a href="{% url 'main:delete_users' object.pk %}" class="btn btn-danger btn-lg btn-block custom-button">Удалить клиента</a>
  </div>
</div>
    {%endfor%}
</div>

{% endblock %}